"""
backend/core/state.py

This file defines the shared state used by all AI agents.

Each agent reads from and writes to the same state object.
Using a shared contract ensures that all agents can communicate
correctly through the LangGraph workflow.
"""

from typing import TypedDict


class DefinitionItem(TypedDict):
    """
    Represents an important term extracted from the study material.
    """

    term: str
    definition: str


from typing import TypedDict
from typing_extensions import NotRequired


class QuizItem(TypedDict):
    """
    Represents one question generated by the Quiz Generator Agent.
    """

    question: str
    type: str
    correct_answer: str
    explanation: str
    choices: NotRequired[list[str]]


class StudyPlanItem(TypedDict):
    """
    Represents one day in the generated study plan.
    """

    day: int
    topics: list[str]
    difficulty: str
    estimated_hours: float


class StudyState(TypedDict):
    """
    Shared state passed between all LangGraph agents.
    """

    raw_text: str

     # PDF input fields
    pdf_path: str
    pdf_bytes: bytes


    # User Input 

    raw_text: str
    study_days: int
    difficulty: str

    #  Summarization Agent

    summary: str
    key_topics: list[str]
    definitions: list[DefinitionItem]

    #  Quiz Generator Agent 

    quiz: list[QuizItem]

    #  Study Planner Agent 

    study_plan: list[StudyPlanItem]

    #  Security & Monitoring 

    blocked: bool
    security_reason: str
    execution_logs: list[str]